"""delete phone num from user

Revision ID: 98f077cf36cb
Revises: fc73c48ad7cd
Create Date: 2020-08-13 16:47:35.194370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f077cf36cb'
down_revision = 'fc73c48ad7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
